// <auto-generated />
using System;
using BackAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231015112250_Initial7")]
    partial class Initial7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackAPI.Models.Appartenir", b =>
                {
                    b.Property<int>("Id_apart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_apart");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_apart"));

                    b.Property<int>("Capacite")
                        .HasColumnType("integer")
                        .HasColumnName("capacite");

                    b.Property<int>("Id_aeronef")
                        .HasColumnType("integer")
                        .HasColumnName("id_aeronef");

                    b.Property<int>("Id_classe")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.HasKey("Id_apart");

                    b.HasIndex("Id_aeronef");

                    b.HasIndex("Id_classe");

                    b.ToTable("appartenir");
                });

            modelBuilder.Entity("BackAPI.Models.Avion", b =>
                {
                    b.Property<int>("Id_aeronef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_aeronef");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_aeronef"));

                    b.Property<string>("Type_aeronef")
                        .HasColumnType("text")
                        .HasColumnName("type_aeronef");

                    b.HasKey("Id_aeronef");

                    b.ToTable("avion");
                });

            modelBuilder.Entity("BackAPI.Models.ClasseService", b =>
                {
                    b.Property<int>("Id_classe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_classe"));

                    b.Property<int>("Num_siege")
                        .HasColumnType("integer")
                        .HasColumnName("num_siege");

                    b.Property<string>("Type_classe")
                        .HasColumnType("text")
                        .HasColumnName("type_classe");

                    b.HasKey("Id_classe");

                    b.ToTable("classeservice");
                });

            modelBuilder.Entity("BackAPI.Models.Itineraire", b =>
                {
                    b.Property<int>("Id_itineraire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_itineraire");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_itineraire"));

                    b.Property<string>("Aeroport_arrive")
                        .HasColumnType("text")
                        .HasColumnName("aeroport_arrive");

                    b.Property<string>("Aeroport_depart")
                        .HasColumnType("text")
                        .HasColumnName("aeroport_depart");

                    b.HasKey("Id_itineraire");

                    b.ToTable("itineraire");
                });

            modelBuilder.Entity("BackAPI.Models.Passager", b =>
                {
                    b.Property<int>("Id_passager")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_passager");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_passager"));

                    b.Property<string>("Adresse_passager")
                        .HasColumnType("text")
                        .HasColumnName("adresse_passager");

                    b.Property<string>("Email_passager")
                        .HasColumnType("text")
                        .HasColumnName("email_passager");

                    b.Property<string>("Nom_passager")
                        .HasColumnType("text")
                        .HasColumnName("nom_passager");

                    b.Property<long>("Num_passeport")
                        .HasColumnType("bigint")
                        .HasColumnName("num_passeport");

                    b.Property<long>("Phone_passager")
                        .HasColumnType("bigint")
                        .HasColumnName("phone_passager");

                    b.Property<string>("Prenom_passager")
                        .HasColumnType("text")
                        .HasColumnName("prenom_passager");

                    b.HasKey("Id_passager");

                    b.ToTable("passager");
                });

            modelBuilder.Entity("BackAPI.Models.Reservation", b =>
                {
                    b.Property<int>("Num_reservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("num_reservation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Num_reservation"));

                    b.Property<DateTime>("Date_reservation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_reservation");

                    b.Property<int>("Id_classe")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.Property<int>("Id_passager")
                        .HasColumnType("integer")
                        .HasColumnName("id_passager");

                    b.Property<int>("Id_vol")
                        .HasColumnType("integer")
                        .HasColumnName("id_vol");

                    b.HasKey("Num_reservation");

                    b.HasIndex("Id_classe");

                    b.HasIndex("Id_passager");

                    b.HasIndex("Id_vol");

                    b.ToTable("reservation");
                });

            modelBuilder.Entity("BackAPI.Models.Tarif", b =>
                {
                    b.Property<int>("Id_tarif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tarif");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_tarif"));

                    b.Property<int>("Id_classe")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.Property<int>("Id_vol")
                        .HasColumnType("integer")
                        .HasColumnName("id_vol");

                    b.Property<double>("Montant_tarif")
                        .HasColumnType("double precision")
                        .HasColumnName("montant_tarif");

                    b.HasKey("Id_tarif");

                    b.HasIndex("Id_classe");

                    b.HasIndex("Id_vol");

                    b.ToTable("tarif");
                });

            modelBuilder.Entity("BackAPI.Models.Utulisateur", b =>
                {
                    b.Property<int>("Num_matricule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("num_matricule");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Num_matricule"));

                    b.Property<string>("Adresse_user")
                        .HasColumnType("text")
                        .HasColumnName("adresse_user");

                    b.Property<string>("Email_user")
                        .HasColumnType("text")
                        .HasColumnName("email_user");

                    b.Property<string>("Mdp_user")
                        .HasColumnType("text")
                        .HasColumnName("mdp_user");

                    b.Property<string>("Nom_user")
                        .HasColumnType("text")
                        .HasColumnName("nom_user");

                    b.Property<long>("Phone_user")
                        .HasColumnType("bigint")
                        .HasColumnName("phone_user");

                    b.Property<string>("Prenom_user")
                        .HasColumnType("text")
                        .HasColumnName("prenom_user");

                    b.Property<string>("Role_user")
                        .HasColumnType("text")
                        .HasColumnName("role_user");

                    b.HasKey("Num_matricule");

                    b.ToTable("utilisateur");
                });

            modelBuilder.Entity("BackAPI.Models.Vol", b =>
                {
                    b.Property<int>("Id_vol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_vol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_vol"));

                    b.Property<DateTime>("Date_depart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_depart");

                    b.Property<DateTime>("Heure_depart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("heure_depart");

                    b.Property<int>("Id_aeronef")
                        .HasColumnType("integer")
                        .HasColumnName("id_aeronef");

                    b.Property<int>("Id_itineraire")
                        .HasColumnType("integer")
                        .HasColumnName("id_itineraire");

                    b.Property<string>("Num_vol")
                        .HasColumnType("text")
                        .HasColumnName("num_vol");

                    b.Property<double>("Remboursement")
                        .HasColumnType("double precision")
                        .HasColumnName("remboursement");

                    b.HasKey("Id_vol");

                    b.HasIndex("Id_aeronef");

                    b.HasIndex("Id_itineraire");

                    b.ToTable("vol");
                });

            modelBuilder.Entity("BackAPI.Models.Appartenir", b =>
                {
                    b.HasOne("BackAPI.Models.Avion", "Avion")
                        .WithMany()
                        .HasForeignKey("Id_aeronef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackAPI.Models.ClasseService", "ClasseService")
                        .WithMany()
                        .HasForeignKey("Id_classe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avion");

                    b.Navigation("ClasseService");
                });

            modelBuilder.Entity("BackAPI.Models.Reservation", b =>
                {
                    b.HasOne("BackAPI.Models.ClasseService", "ClasseService")
                        .WithMany()
                        .HasForeignKey("Id_classe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackAPI.Models.Passager", "Passager")
                        .WithMany()
                        .HasForeignKey("Id_passager")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackAPI.Models.Vol", "Vol")
                        .WithMany()
                        .HasForeignKey("Id_vol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClasseService");

                    b.Navigation("Passager");

                    b.Navigation("Vol");
                });

            modelBuilder.Entity("BackAPI.Models.Tarif", b =>
                {
                    b.HasOne("BackAPI.Models.ClasseService", "ClasseService")
                        .WithMany()
                        .HasForeignKey("Id_classe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackAPI.Models.Vol", "Vol")
                        .WithMany()
                        .HasForeignKey("Id_vol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClasseService");

                    b.Navigation("Vol");
                });

            modelBuilder.Entity("BackAPI.Models.Vol", b =>
                {
                    b.HasOne("BackAPI.Models.Avion", "Avion")
                        .WithMany()
                        .HasForeignKey("Id_aeronef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackAPI.Models.Itineraire", "Itineraire")
                        .WithMany()
                        .HasForeignKey("Id_itineraire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avion");

                    b.Navigation("Itineraire");
                });
#pragma warning restore 612, 618
        }
    }
}
