// <auto-generated />
using System;
using BackAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231015100336_Initial3")]
    partial class Initial3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackAPI.Models.Appartenir", b =>
                {
                    b.Property<int>("Id_apart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_apart");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_apart"));

                    b.Property<int?>("AvionId_aeronef")
                        .HasColumnType("integer");

                    b.Property<int>("Capacite")
                        .HasColumnType("integer")
                        .HasColumnName("capacite");

                    b.Property<int?>("ClasseServiceId_classe")
                        .HasColumnType("integer");

                    b.Property<int>("Id_aeronef")
                        .HasColumnType("integer")
                        .HasColumnName("id_aeronef");

                    b.Property<int>("Id_classe")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.HasKey("Id_apart");

                    b.HasIndex("AvionId_aeronef");

                    b.HasIndex("ClasseServiceId_classe");

                    b.ToTable("appartenir");
                });

            modelBuilder.Entity("BackAPI.Models.Avion", b =>
                {
                    b.Property<int>("Id_aeronef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_aeronef");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_aeronef"));

                    b.Property<string>("Type_aeronef")
                        .HasColumnType("text")
                        .HasColumnName("type_aeronef");

                    b.HasKey("Id_aeronef");

                    b.ToTable("avion");
                });

            modelBuilder.Entity("BackAPI.Models.ClasseService", b =>
                {
                    b.Property<int>("Id_classe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_classe"));

                    b.Property<int>("Num_siege")
                        .HasColumnType("integer")
                        .HasColumnName("num_siege");

                    b.Property<string>("Type_classe")
                        .HasColumnType("text")
                        .HasColumnName("type_classe");

                    b.HasKey("Id_classe");

                    b.ToTable("classeservice");
                });

            modelBuilder.Entity("BackAPI.Models.Itineraire", b =>
                {
                    b.Property<int>("Id_itineraire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_itineraire");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_itineraire"));

                    b.Property<string>("Aeroport_arrive")
                        .HasColumnType("text")
                        .HasColumnName("aeroport_arrive");

                    b.Property<string>("Aeroport_depart")
                        .HasColumnType("text")
                        .HasColumnName("aeroport_depart");

                    b.HasKey("Id_itineraire");

                    b.ToTable("itineraire");
                });

            modelBuilder.Entity("BackAPI.Models.Appartenir", b =>
                {
                    b.HasOne("BackAPI.Models.Avion", "Avion")
                        .WithMany()
                        .HasForeignKey("AvionId_aeronef");

                    b.HasOne("BackAPI.Models.ClasseService", "ClasseService")
                        .WithMany()
                        .HasForeignKey("ClasseServiceId_classe");

                    b.Navigation("Avion");

                    b.Navigation("ClasseService");
                });
#pragma warning restore 612, 618
        }
    }
}
